variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'Laboratorium/DoctorsApp'
  DOCKER_IMAGE: 'roundel/uaim_lab_doctors-data'

default:
  before_script:
    - cd $SOURCE_CODE_PATH

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - lint
  - build
  - test
  - publish
  - deploy

cache:
  key: ${CI_JOB_NAME} 
  paths:
    - '$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*/project.assets.json'
    - '$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*/*.csproj.nuget.*'
    - '$SOURCE_CODE_PATH/$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

lint:lab-dd:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  stage: lint
  tags:
    - integration
  script:
    - 'dotnet tool restore'
    - 'dotnet dotnet-format --check'

build:lab-dd:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  stage: build
  tags:
    - integration
  script:
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet build --no-restore'
  needs:
    - job: lint:lab-dd

test:lab-dd:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  stage: test
  tags:
    - integration
  script:
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet test --no-restore --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - '$SOURCE_CODE_PATH/**/*test-result.xml'
    reports:
      junit:
        - '$SOURCE_CODE_PATH/**/*test-result.xml'
  needs:
    - job: build:lab-dd

publish:lab-dd:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - delivery
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$REGISTRY_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --cache-repo="${DOCKER_IMAGE}-cache" --context Doctors --dockerfile Doctors/Dockerfile --destination $DOCKER_IMAGE:latest
  only:
    refs: 
      - master
  needs:
    - job: test:lab-dd

deploy:lab-dd:
  stage: deploy
  image: bitnami/kubectl
  tags:
    - deployment
  before_script:
    - export KUBECONFIG=$(mktemp)
    - echo ${K8S_CONFIG} | base64 -d > ${KUBECONFIG}
  script:
    - kubectl apply -f "/builds/$CI_PROJECT_PATH/$SOURCE_CODE_PATH/k8s"
    - kubectl rollout restart statefulset lab-doctors-data
  only:
    refs:
    - master
  needs:
    - job: publish:lab-dd
