version: "3.9"
services:
  roomselector:
    image: roundel/uaim_lab_rooms-app
    environment:
      EXM_ROOM_SEL_ServiceConfiguration__DoctorsUrl: "http://doctors"
      EXM_ROOM_SEL_ServiceConfiguration__RoomsUrl: "http://rooms"

  rooms:
    image: roundel/uaim_lab_rooms-data

  doctors:
    image: roundel/uaim_lab_doctors-data

  webapp:
    image: roundel/uaim_lab_webapp
    environment:
      EXM_WEB_ServiceConfiguration__BackendUrl: "http://roomselector"
    ports:
      - "8080:80"
