version: "3.9"
services:
  roomselector:
    build:
      context: ./ExaminationRoomsSelector/App
    environment:
      EXM_ROOM_SEL_ServiceConfiguration__DoctorsUrl: "http://doctors"
      EXM_ROOM_SEL_ServiceConfiguration__RoomsUrl: "http://rooms"

  rooms:
    build:
      context: ./ExaminationRooms/ExaminationRooms

  doctors:
    build:
      context: ./DoctorsApp/Doctors

  webapp:
    build:
      context: ./WebApp
    environment:
      EXM_WEB_ServiceConfiguration__BackendUrl: "http://roomselector"
    ports:
      - "8080:80"
