apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lab-doctors-data
  namespace: uaim
spec:
  selector:
    matchLabels:
      app: lab-doctors-data
  serviceName: lab-doctors-data
  template:
    metadata:
      name: lab-doctors-data
      labels:
        app: lab-doctors-data
    spec:
      containers:
        - name: data
          image: roundel/uaim_lab_doctors-data
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
