apiVersion: v1
kind: Service
metadata:
  name: doctors-data
  namespace: uaim
spec:
  selector:
    app: doctors-data
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
