version: "3.9"
services:
  doctors-data:
    build:
      context: ./DoctorsData

  patients-data:
    image: dadurex/uaim_project_patients_data

  doctors-app:
    image: dadurex/uaim_project_doctors_app
    ports:
      - "42069:80"
    environment:
      DOC_APP_ServiceConfiguration__DoctorsDataUrl: "http://doctors-data"
      DOC_APP_ServiceConfiguration__PatientsDataUrl: "http://patients-data"

  patients-app:
    build:
      context: ./PatientsApp
    ports:
      - "42070:80"
    environment:
      PAT_APP_ServiceConfiguration__DoctorsDataUrl: "http://doctors-data"
      PAT_APP_ServiceConfiguration__PatientsDataUrl: "http://patients-data"
