version: "3.9"
services:
  doctors-data:
    image: roundel/uaim_project_doctors-data

  patients-data:
    image: dadurex/uaim_project_patients_data

  doctors-app:
    image: dadurex/uaim_project_doctors_app

  patients-app:
    image: roundel/uaim_project_patients-app

  doctors-web:
    image: roundel/uaim_project_doctors-web
