version: "3.9"
services:
  doctors-data:
    image: bwalusiak/uaim_project_doctors_data

  patients-data:
    image: dadurex/uaim_project_patients_data

  doctors-app:
    image: dadurex/uaim_project_doctors_app
    environment:
      DOC_APP_ServiceConfiguration__DoctorsDataUrl: "http://doctors-data"
      DOC_APP_ServiceConfiguration__PatientsDataUrl: "http://patients-data"

  patients-app:
    image: bwalusiak/uaim_project_patients_app
    environment:
      PAT_APP_ServiceConfiguration__DoctorsDataUrl: "http://doctors-data"
      PAT_APP_ServiceConfiguration__PatientsDataUrl: "http://patients-data"

  doctors-web:
    image: bwalusiak/uaim_project_doctors_web
    ports:
      - 42069:80
    environment:
      DOC_WEB_ServiceConfiguration__BackendUrl: "http://doctors-app"
