apiVersion: v1
kind: Service
metadata:
  name: lab-selector
  namespace: uaim
spec:
  selector:
    app: lab-selector
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
