variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'Projekt/DoctorsData'

default:
  before_script:
    - cd Projekt/DoctorsData

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - lint
  - build
  - test
  - publish
  - deploy

cache:
  key: ${CI_JOB_NAME} 
  paths:
    - '$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*/project.assets.json'
    - '$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*/*.csproj.nuget.*'
    - '$SOURCE_CODE_PATH/$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

lint:dd:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  stage: lint
  script:
    - 'dotnet tool restore'
    - 'dotnet dotnet-format --check'

build:dd:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  stage: build
  script:
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet build --no-restore'
  needs:
    - job: lint:dd

test:dd:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  stage: test
  script:
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet test --no-restore --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - '$SOURCE_CODE_PATH/**/*test-result.xml'
    reports:
      junit:
        - '$SOURCE_CODE_PATH/**/*test-result.xml'
  needs:
    - job: build:dd

publish:dd:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$REGISTRY_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --cache-repo="${DD_IMAGE}-cache" --context . --dockerfile Dockerfile --destination $DD_IMAGE:latest
  only:
    refs:
    - master
  needs:
    - job: test:dd

deploy:dd:
  stage: deploy
  image: bitnami/kubectl
  before_script:
    - export KUBECONFIG=$(mktemp)
    - echo ${K8S_CONFIG} | base64 -d > ${KUBECONFIG}
  script:
    - kubectl apply -f "/builds/$CI_PROJECT_PATH/Miniprojekty/Kubernetes/DoctorsData"
    - kubectl rollout restart statefulset doctors-data
  only:
    refs:
    - master
  needs:
    - job: publish:dd
