image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
  # 1) Name of directory where restore and build objects are stored.
  OBJECTS_DIRECTORY: 'obj'
  # 2) Name of directory used for keeping restored dependencies.
  NUGET_PACKAGES_DIRECTORY: '.nuget'

default:
  before_script:
    - cd Projekt/PatientsApp

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - lint
  - build
  - test
  - publish

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - 'project.assets.json'
    - '*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

lint:pa:
  stage: lint
  script:
    - 'dotnet tool restore'
    - 'dotnet dotnet-format --check'

build:pa:
  stage: build
  script:
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet build --no-restore'
  needs:
    - job: lint:pa

test:pa:
  stage: test
  script:
    - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
    - 'dotnet test --no-restore --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - 'Projekt/PatientsApp/**/*test-result.xml'
    reports:
      junit:
        - 'Projekt/PatientsApp/**/*test-result.xml'
  needs:
    - job: build:pa

publish:pa:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$REGISTRY_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --cache-repo="${PA_IMAGE}-cache" --context . --dockerfile Dockerfile --destination $PA_IMAGE:latest
  only:
    refs: 
      - master
  needs:
    - job: test:pa
